name: Deploy to Webspace (SSH)

on:
  push:
    branches: [ "main" ]   # ggf. auf "master" ändern

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Dateien via SSH/rsync synchronisieren (SFTP/SSH, Port 22)
      - name: Sync files (SFTP/SSH)
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ vars.TARGET_SERVER }}
          remote-user: ${{ vars.REMOTE_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: 22
          destination-path: ${{ vars.DEST_PATH }}
          # Zum Testen ohne Änderungen:
          # rsync-options: --dry-run
