name: Deploy to Webspace (SSH)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync files (SFTP/SSH)
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: home33661130.1and1-data.host
          remote-user: p8158542
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: 22
          destination-path: ~/htdocs/
          # Zum Testen erst dry-run einschalten (optional):
          # rsync-options: --dry-run
